version: "3.9"

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: meyr1n27/foodgram_backend:latest
    restart: always
    env_file:
      - .env
    volumes:
      - static:/app/collected_static/static
      - media:/app/media
      - ./backend/data:/app/data
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: meyr1n27/foodgram_frontend:latest
    command: >
      sh -c "cp -r /app/build/* /frontend_build/"
    volumes:
      - frontend_build:/frontend_build

  gateway:
    image: meyr1n27/foodgram_gateway:latest
    restart: always
    ports:
      - "7000:80"
    volumes:
      - static:/static
      - media:/media
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media:
  frontend_build: